/* Create Spring Schema  */
-- SCHEMA: spring

-- DROP SCHEMA IF EXISTS spring ;

CREATE SCHEMA IF NOT EXISTS spring
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA spring TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA spring
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA spring
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA spring
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA spring
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
