alter user postgres WITH PASSWORD 'posgres';



-- SCHEMA: data_241

-- DROP SCHEMA IF EXISTS data_241 ;

CREATE SCHEMA IF NOT EXISTS data_241
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_241 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_241
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;


-- SCHEMA: rules_241

-- DROP SCHEMA IF EXISTS rules_241 ;

CREATE SCHEMA IF NOT EXISTS rules_241
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_241 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_241
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;


-- SCHEMA: customer_241

-- DROP SCHEMA IF EXISTS customer_241 ;

CREATE SCHEMA IF NOT EXISTS customer_241
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_241 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_241
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
