apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
  labels:
    name:  nginx-3
spec:
  containers:
  - name:  nginx-3
    image:  nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: <Port>
