-- SCHEMA: comms_customer_88

-- DROP SCHEMA IF EXISTS comms_customer_88 ;

CREATE SCHEMA IF NOT EXISTS comms_customer_88
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA comms_customer_88 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_customer_88
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_customer_88
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_customer_88
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_customer_88
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: comms_data_88

-- DROP SCHEMA IF EXISTS comms_data_88 ;

CREATE SCHEMA IF NOT EXISTS comms_data_88
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA comms_data_88 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_data_88
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_data_88
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_data_88
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_data_88
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: comms_rules_88

-- DROP SCHEMA IF EXISTS comms_rules_88 ;

CREATE SCHEMA IF NOT EXISTS comms_rules_88
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA comms_rules_88 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_rules_88
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_rules_88
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_rules_88
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA comms_rules_88
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;
