apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    #ports:
      #- containerPort: <Port>
