apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: postgres
spec:
  containers:
  - name: postgres
    image: postgres
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: <Port>
