/******* SCHEMA CREATION SCRIPTS ********/
-- SCHEMA: customer_88

-- DROP SCHEMA IF EXISTS customer_88 ;

CREATE SCHEMA IF NOT EXISTS customer_88
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA customer_88 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_88
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_88
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_88
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA customer_88
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: rules_88

-- DROP SCHEMA IF EXISTS rules_88 ;

CREATE SCHEMA IF NOT EXISTS rules_88
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA rules_88 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_88
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_88
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_88
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA rules_88
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- SCHEMA: data_88

-- DROP SCHEMA IF EXISTS data_88 ;

CREATE SCHEMA IF NOT EXISTS data_88
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA data_88 TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_88
GRANT ALL ON TABLES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_88
GRANT ALL ON SEQUENCES TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_88
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA data_88
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

/******* USEFUL QUERIES ********/
