
-- Pega-BIX:08-07 - rule set 
DROP TABLE  SYSTEM.OKPM_NOTIFICATIONS_WORK CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.OKPM_NOTIFICATIONS_WORK
(
    "PZINSKEY" VARCHAR2(256 CHAR) NULL,
    "PXEXTRACTIDENTIFIER" VARCHAR2(256 CHAR) NULL,
    "PXEXTRACTDATETIME" TIMESTAMP NULL,
    "PYID" VARCHAR2(32 CHAR) PRIMARY KEY
)
;

select * from SYSTEM.OKPM_NOTIFICATIONS_WORK;